# fly.toml app configuration file generated for lifeone-broken-star-3480 on 2024-01-22T05:28:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lifeone-broken-star-3480"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"
# image = "nginx"  


[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
